# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         sendxmpp
version:      0.0.8
version_from: sendxmpp
installdirs:  site
requires:
    Getopt::Long:                  2
    Net::XMPP:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
